### ISSUE TITLE
repoのインストールができない

### ISSUE THREAD

**Issue by cafecat6503** [cafecat6503/EasyBuildTool#1]
export PATH=~/bin:$PATH この処理がうまく行かない。自分が無知なだけだと思うけど・・　手動で実行すればできる。

**Comment by droidfivex** [comment]
bash環境を想定し、~/.bashrc に追記してから source ~/.bashrc しちゃえばいいかと思う

**Comment by droidfivex** [comment]
READMEに内容が未定と書かれていたのでスクリプトが書かれていないかと思ってしまった為先ほどスクリプトを見ずに回答したのだが、恐らく `export PATH=~/bin:$PATH` を `export PATH=~/bin:\$PATH` にすれば使えるようになるかと
$ マークにてPATH変数の展開を行う為、実行されるのは `export PATH=~/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games` のような形になっていたと思われる

**Comment by droidfivex** [comment]
先ほどまでのコメントはREADMEを見てシェルスクリプトがないものだと思いコメントしてしまい申し訳ない
シェル内でいくらPATHを書き換えても親シェルには引き継がれないため、失敗したと勘違いしたのだと思われる
スクリプト内のrepoのインストール手順に `echo $PATH` を追記し実行したところ存在し、また `type repo` した時存在が確認できた
